<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script type="text/javascript">

	//check if the page was called via ajax - if not, redirect to index.html, crawlers will ignore this and fetch the simple HTML pageHash
	function checkIfAsgard(){

		var thisHref = window.location.href;
		thisHref = thisHref.substr(thisHref.lastIndexOf('/') + 1);
		thisHref = thisHref.split(".html");

		if(typeof this["isAsgard"] === 'undefined')
			window.location.href = "index.html"+"#"+thisHref[0];

	}

	//check if the page was called via ajax - if not, redirect to index.html, crawlers will ignore this and fetch the simple HTML pageHash
	checkIfAsgard();

	//masonry portfolio
	masonryPortfolio();

	//add gallery icons etc
	prepareGallery();
	
	function animateThis(){

		//animate masonry
		animatePage("", "gallery");

	}

	//click on simple or masonry portfolio items
	portfolioClicked();

</script>

<title>Asgard - Masonry type portfolio</title>
</head>

<body>

<!-- grey background -->
<div class="full-width-background">
	<img src="images/backgrounds/grey2.jpg" alt="grey2" />
</div>
<!-- grey background -->

<div id="masonryPortfolio">

	<div class="masonryImage">
		<img class="item link" src="images/thumbnails/rose-white-delphinium.png" alt="1-jpg" />
		<span class="description">White Delphinium and Red Roses</span>
		<p>
		The unique selection of White Delpinium in this arrangement gives a delicate softness to the presence of the red roses.  The lenght of the Delphinium is used to its full extent, dramatically creating a focal point in the wedding venue.
		</p>
	</div>

	<div class="masonryImage">
		<img class="item blog" src="images/thumbnails/single-rose.png" alt="2-jpg" />
		<span class="description">Single White Rose</span>
		<p>
		Sometimes simplicity bears the greater impact.  This simple and elegant arrangement is ideal for the center of circular tables when a presence of flowers is required but without taking over the space provided.
		</p>
	</div>

		<div class="masonryImage">
		<img class="item music" src="images/thumbnails/white-anthurium.png" alt="3-jpg" />
		<span class="description">Rose and White Anthurium Table Arrangement</span>
		<p>
		Roses and White Anthurium are fashioned in an unique arrangement which fit perfectly for circular or U-form table settings.  It sits in its own space without the use of vases or glass.
		</p>
	</div>

	<div class="masonryImage">
		<img class="item link" src="images/thumbnails/Christmas_wedding_arrangement.png" alt="5-jpg" />
		<span class="description">Christmas Wedding Arrangement</span>
		<p>
		This table arrangement is ideal for Christmas Wedding event as it uses a willow wreath as its base and red roses.</p>
	</div>

	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/amaryllis.png" alt="" />
		<span class="description">Amaryllis Table Arrangement</span>
		<p>
		Amaryllis is also a good option for those table arrangements needing some height.  This concial arrangement	includes other flowers but allows the amaryllis to take center-stage.</p>
	</div>
	
	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/amaryllis-taable-arrangements.png" alt="11-jpg" />
		<span class="description">Amaryllis Table Arrangements</span>
		<p>
		Amaryllis is used with taller lily glasses.  The use of red christmas baubles, a favourite of the bride, shows that flowers can include a myriad of elements special to the bridal couple.
	</div>

	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/brandy-lights.png" alt="8-jpg" />
		<span class="description">Submersible Lights with Amaryllis</span>
		<p>
		The use of Brandy Glasses with submersible lights also create a different atmospher especially when the main flowers are echoed in the arrangement.
		</p>
	</div>
	<div class="masonryImage">
		<img class="item link" src="images/thumbnails/use_0393.JPG" alt="2-jpg" />
		<span class="description">A Selection of table arrangements</span>
		<p>
		The use of accessories can valuably add to the atmosphere of the wedding, lanterns, hearts, candelabras all add to the overall effect.
		</p></div>

	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/blue-gentiana.png" alt="2-jpg" />
		<span class="description">Blue Gentiana</span>
		<p>
		Tall wedding arrangements are useful in larger, high vaulted rooms where the focal point of an arrangement should reach upwards to take advantage of these unique interiors.
		</p>
	</div>
	
	<div class="masonryImage">
		<img class="item link" src="images/thumbnails/bouquet-set.png" alt="1-jpg" />
		<span class="description">Pastel Purple and White Rose Bouquet Set</span>
		<p>
The principle bouquet for the bride is a shower bouquet, this typical cascades down displaying the flowers in full view.  The two bridesmaids' bouquets are domed bouquets with all the flowers best viewed from above.  These two aspects create a good contrast to the wedding party, while using the same flowers a clear distinction is made between the Bride's bouquet and those of the bridesmaids.
</p>
	</div>

	<div class="masonryImage">
		<img class="item blog" src="images/thumbnails/hair-piece.png" alt="2-jpg" />
		<span class="description">Bridesmaid's Hair Piece</span>
		<p>
Using flowers as hairpieces is another great idea to reinforce the flowers being used in your wedding theme.  As they can be custom made with the bridal flowers in mind it also can be a convenient way to provide accessories that match.
</p>
	</div>

	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/two-rose.png" alt="4-jpg" />
		<span class="description">Spray Rose Wedding Bouquet</span>
		<p>
The use of both spray and large roses are anther option especially in shower bouquets or if a more dynamic domed bouquet is desired.  The difference in size and colour	creates an interesting contrast.
		</p></div>

	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/wedding_arch.png" alt="Wedding Arch" />
		<span class="description">Wedding Arch</span>
		
		<p>
		Wedding Arches add to the overall atmosphere of your wedding and the continued use of the chosen wedding flowers builds the style and colour chosen for the wedding.
		.</p>
	</div>

	

	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/bridesmaid-bouquet.png" alt="" />
		<span class="description">Christmas Bridesmaid&nbsp;s Bouquet</span>
		<p>
		Smaller bouquets for the bridesmaids can include elements of your wedding theme that may be absent from the bridal bouquet.  It is often worthwhile to cross match the bridesmaid's dress colour with focal flowers in the bridal bouquet.  Likewise if the bridesmaid's flowers are an exact match of their dress colour the bouquets may lose their impact in the wedding photographs.
		</p>	
	</div>

	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/shower-bouquet.png" alt="10-jpg" />
		<span class="description">Pastel Shower Bouquet</span>
		<p>
		This selection of flowers was choosen with a purple theme in mind, however the selection of a variety of tones and shades of purple really help to make this bouquet stand out and hold interest.  A good selection of veronica, lisianthus, pastel purple roses and erynigium all provide different textures for this bouquet.
		</p>
	</div>

	

	<div class="masonryImage">
		<img class="item link" src="images/thumbnails/carmen-rose-bouquet-small1.png" alt="12-jpg" />
		<span class="description">Carmen Bouquet</span>
		<p>
		When one considers the work taken to create this bouquet it can only add to the meaning of love that it represents.  A total of approximately twelve roses make up this one carmen rose, each petal is removed and added onto the central rose.  This beautiful creation shows the skill of the florist and more importantly the beauty of the bouquet.
		</p>
	</div>

	<div class="masonryImage">
		<img class="item image" src="images/thumbnails/pink-rose-wedding-bouquet.jpg" alt="" />
		<span class="description">Pink rose and waxflower domed bouquet</span>
		<p>Another smaller bouquet which can be used as a Bridal bouquet or as a bridesmaid's bouquet.  The selection of the pale pink and flower heads of the waxflower creates a petite and rather elegante bouquet.
		</p>
	</div>
	

</div>

</body>
</html>